version: '3.8'

services:
  frontend-erp:
    container_name: frontend-erp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/mydb
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
